# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81a15932b37c81500b6db9f6f5c22db7ce1fcfa6610dc69b14a6801f5dfedf0c79f04c8b9ef9c3bfb3bf38d5329185a6aa6fbe03ee8fa98eed1e0da34c6d14d7

test:
  secret_key_base: 920a4b3b12387dad6bf1a4e85f353414c27e302f970c5d29bd21b7dcefe7dd266fd8f3b294943134fcbdfd0ccddc95b40afd3acd26ce65535efe573b03217867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
